version: 2.1
jobs:
  release:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
workflows:
  do_build:
    jobs:
      - release:
          context: private_packages
          filters:
            branches:
              only:
                - dev
                - stage
                - main
